#! /usr/bin/env fish

# turn a symlink into a recursive copy of the target

set argc (count $argv)
if test $argc -ne 1; echo "argc != 1; argc == $argc"; return 1; end

set link $argv[1]

if not test -L $link
    echo "either cannot access $link, or it is not a symlink"
    return 1
end

set targ (realpath $link)

if not test -e $targ
    echo "cannot access link target: $targ"
    return 1
end

echo "removing $link"
rm -- $link
    or return 1

echo "copying $targ to $link"
cp -rPTf -- $targ $link
    or return 1

echo "done; ll $link"
ll $link
