#! /usr/bin/env zsh

set -e

nix build --no-link -L --show-trace --impure ~/projects/nix/sys/personal ${argv}
nix profile remove 0
nix run --impure ~/projects/nix/sys/personal#activate-default ${argv}
