#! /usr/bin/zsh

set -e

NEWLINE=$'\n'

echoerr() {
	echo $@ 1>&2;
}

output_file=$(mktemp --tmpdir wgFile.XXXXXX)

REPLACE_STR=$(cat <<-END
[WireGuardPeer]
PublicKey = \$1
AllowedIPs = \$2
Endpoint = \$3
END
)

for file in $@; do
	sd -p -f ms '.*\[Peer\]\s+PublicKey\s*=\s*(?P<public_key>[^\s]+)\s+AllowedIPs\s*=\s*(?P<allowed_ips>[^\s]+)\s+Endpoint\s*=\s*(?P<endpoint>[^\s]+)\s*.*' "# ${file:t:r}${NEWLINE}${REPLACE_STR}${NEWLINE}${NEWLINE}" $file >> $output_file
done

cat $output_file
